// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXoLj_sP0A35Bd39p0-w-LfY0yn4cwxZM',
    appId: '1:791108439820:web:aa5b1a7acb768f826e0329',
    messagingSenderId: '791108439820',
    projectId: 'filmcock-99086',
    authDomain: 'filmcock-99086.firebaseapp.com',
    storageBucket: 'filmcock-99086.firebasestorage.app',
    measurementId: 'G-CL8D07JNVT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN2n3ete2M8v0k-_CAcTMtz4lCiDSUPZM',
    appId: '1:791108439820:android:73242e537278c94c6e0329',
    messagingSenderId: '791108439820',
    projectId: 'filmcock-99086',
    storageBucket: 'filmcock-99086.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTdxvS4bxSrm58TjPmhqKO4rgvpmS3jyc',
    appId: '1:791108439820:ios:845620a4589c99126e0329',
    messagingSenderId: '791108439820',
    projectId: 'filmcock-99086',
    storageBucket: 'filmcock-99086.firebasestorage.app',
    androidClientId: '791108439820-f488k716i3gbpfiqarecmbcvp14hidqm.apps.googleusercontent.com',
    iosClientId: '791108439820-j5irkq0gductlpmnrlfj43d3fskvhkde.apps.googleusercontent.com',
    iosBundleId: 'com.example.filmcockApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTdxvS4bxSrm58TjPmhqKO4rgvpmS3jyc',
    appId: '1:791108439820:ios:845620a4589c99126e0329',
    messagingSenderId: '791108439820',
    projectId: 'filmcock-99086',
    storageBucket: 'filmcock-99086.firebasestorage.app',
    androidClientId: '791108439820-f488k716i3gbpfiqarecmbcvp14hidqm.apps.googleusercontent.com',
    iosClientId: '791108439820-j5irkq0gductlpmnrlfj43d3fskvhkde.apps.googleusercontent.com',
    iosBundleId: 'com.example.filmcockApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXoLj_sP0A35Bd39p0-w-LfY0yn4cwxZM',
    appId: '1:791108439820:web:38ae42417e5649836e0329',
    messagingSenderId: '791108439820',
    projectId: 'filmcock-99086',
    authDomain: 'filmcock-99086.firebaseapp.com',
    storageBucket: 'filmcock-99086.firebasestorage.app',
    measurementId: 'G-55RH49QCSK',
  );
}
